"use strict";
(() => {
  const H=window.FM_DEEP;if(!H)return;const {S,P,E,R,T,register}=H;
  register({
    "intro/real-financial-assets":{
      deepDive:[
        S("Economic function","Ask what the asset does",["The useful distinction is not physical versus non-physical. A machine, a warehouse, software, a patent and human know-how can all support production and therefore function as real assets. A bond certificate may be physically printed, but economically it remains a financial claim because it reallocates cash flows rather than creating productive capacity by itself.","At the level of the whole economy, financial assets and corresponding liabilities largely cancel. The productive capacity represented by real assets does not. This is why national wealth cannot be increased merely by issuing more claims; the claims must ultimately be supported by productive activity."],[],"Is a patent real or financial? Explain by its economic function, not its physical form."),
        S("Two-sided contract","One instrument, two balance-sheet meanings",["A corporate bond is an asset for the investor because it promises coupons and principal. The same contract is a liability for the issuing company. Common stock is an asset for the shareholder and an equity claim against the corporation. The classification therefore depends on both the instrument and the observer's perspective.","This symmetry is a powerful error check: if one party records a financial claim, identify who owes or supports that claim. The cash flows must have a source."],[],"For a bank deposit, identify the depositor's asset and the bank's corresponding obligation."),
        S("Value creation","Financing supports investment but is not the investment",["Issuing shares or bonds can provide funds, but financing alone does not guarantee value creation. Value is created when the raised funds are invested in real assets or capabilities whose risk-adjusted benefits exceed their costs.","A firm can therefore have a sophisticated financing package and still destroy value if the underlying project has negative NPV. Conversely, a valuable real investment still needs a feasible financing and liquidity plan."],["Real-asset decision: what productive resource is acquired?","Financing decision: which claim funds it?","Value test: do discounted benefits exceed all incremental costs?"],"Why can a positive cash inflow from issuing debt never be counted as project revenue?")
      ],
      termsExtra:[["Productive capacity","Năng lực sản xuất"],["Counterparty","Bên đối tác trong hợp đồng"],["Net wealth","Tài sản ròng"]],
      guidedPractice:[
        P("Easy","Classify four items","Classify a delivery van, a patent used in production, a bank deposit and a corporate bond held by an investor.","Ask whether the item supports production or represents a contractual claim.",["Delivery van: productive physical resource, so real asset.","Patent: productive intangible capability, so real asset.","Bank deposit and corporate bond: contractual claims to cash, so financial assets."],"Real: delivery van and patent. Financial: deposit and bond.","Tangibility is not the rule; economic function is."),
        P("Intermediate","Trace both sides of a bond","A manufacturer issues VND 20 billion of bonds and buys a production line. Identify the real asset, the investor's asset, the issuer's liability and the two cash-flow directions.","Separate the financing transaction from the asset purchase.",["Investors pay cash to the manufacturer and receive bonds.","The manufacturer records bond debt; investors record a bond investment.","The manufacturer pays the equipment supplier and receives the production line.","Future coupons and principal flow from manufacturer to bondholders."],"Production line = real asset; bond = investor financial asset and issuer liability.","The same contract can be an asset and a liability, but the machine is the productive resource."),
        P("Advanced","Does securitization create wealth?","A firm bundles existing receivables and issues securities backed by them. Has the economy automatically gained real wealth at issuance? Explain.","Ask whether productive capacity or expected underlying cash flows changed merely because claims were repackaged.",["Receivables already represented claims on customer payments.","Securitization changes ownership, liquidity and risk allocation of those claims.","It may lower financing costs and indirectly support future investment, but issuance itself does not create a new factory, skill or technology."],"No automatic real-wealth creation; it reallocates and may improve financing efficiency.","Financial engineering can improve allocation without being identical to real investment.")
      ]
    },
    "intro/what-is-finance":{
      deepDive:[
        S("Decision lens","Every finance problem has four coordinates",["Start by identifying the decision maker, the alternatives, the dated cash flows and the uncertainty around them. Only after those coordinates are clear should you select a formula or decision rule.","This structure connects personal finance, corporate finance, investments and public finance. A household choosing a mortgage and a firm choosing a factory both compare alternatives across time, under constraints and uncertainty."],["Perspective: whose cash flows?","Timing: when does each amount occur?","Risk: how reliable is each amount?","Benchmark: what opportunity cost makes alternatives comparable?"],"Why is a large future amount not automatically better than a smaller amount today?"),
        S("Opportunity cost","The discount rate is an economic comparison",["The opportunity cost of capital is the return forgone on the best comparable alternative. It is not chosen merely to make an answer convenient. It should reflect time, risk and the market opportunities available to the decision maker.","Discounting converts dated amounts to a common focal date. Risk analysis then asks whether the expected cash flows and the required return are reasonable. Keeping these ideas separate prevents double-counting risk."],[],"If a safe bank deposit yields 5%, why is 3% an inappropriate discount rate for an equally safe one-year choice?"),
        S("Implementation","A decision is incomplete until it can be financed and managed",["Finance theory moves from evaluation to implementation. A positive-NPV project still requires funding, contractual design, risk management and enough liquidity to survive the timing of payments.","The financial system supplies markets, intermediaries, payment mechanisms and risk-transfer contracts. These institutions reduce frictions but do not remove scarcity or uncertainty."],[],"Name one valuation issue and one implementation issue in buying a home.")
      ],
      sourceCorrections:[
        {title:"Profit, retained earnings and cash are different",body:"Retained earnings is accumulated accounting profit kept in equity; it is not the firm's cash balance. Cash is shown on the balance sheet, while the statement of cash flows explains major cash movements. A profitable firm can lack cash because revenue recognition and cash collection occur at different times."}
      ],
      termsExtra:[["Focal date","Mốc thời gian quy đổi"],["Incremental cash flow","Dòng tiền tăng thêm"],["Opportunity cost of capital","Chi phí cơ hội của vốn"]],
      guidedPractice:[
        P("Easy","Today or next year?","Choose between VND 100 million today and VND 106 million in one year when a comparable safe investment earns 5%.","Move both alternatives to the same date.",["Future value of VND 100 million today at 5% is VND 105 million.","The alternative pays VND 106 million in one year.","Because 106 > 105, the delayed payment is financially superior if risk and liquidity are comparable."],"Choose VND 106 million next year.","A common date makes the alternatives economically comparable."),
        P("Intermediate","Four-coordinate analysis","A student can pay tuition now or take a loan and pay later. List the perspective, cash flows, major risks and benchmark rate needed for analysis.","Do not calculate until the decision map is complete.",["Perspective: the student/household.","Cash flows: tuition paid now versus loan proceeds, fees, installments and any down payment.","Risks: income uncertainty, variable rate, penalties and liquidity needs.","Benchmark: the effective borrowing cost and return available on retained cash."],"A structured decision map, not a single nominal-rate comparison.","Finance begins with framing; formulas implement the frame."),
        P("Advanced","Avoid double-counting risk","A risky project's cash flows were already reduced to certainty-equivalent amounts. Should the analyst also use a large risk premium in the discount rate without adjustment?", "Identify where risk has already entered the valuation.",["Certainty-equivalent cash flows already reduce expected amounts for risk.","A risk-adjusted discount rate is an alternative method of incorporating risk.","Using both without a consistent model can penalize the project twice."],"No; use one coherent risk-adjustment framework or carefully reconcile the two.","Separating expected cash-flow estimation from discount-rate selection prevents hidden double-counting.")
      ]
    },
    "intro/financial-decisions":{
      deepDive:[
        S("Capital budgeting","Choose assets before celebrating financing",["Capital budgeting identifies, forecasts and evaluates long-term investments. Relevant cash flows are incremental: include amounts that occur because the project is accepted and exclude sunk costs that cannot be changed.","The NPV rule connects the project to shareholder value: accept when the present value of incremental benefits exceeds the present value of incremental costs at an appropriate required return."],[],"Would an appraisal fee paid last year change if the project is accepted today?"),
        S("Capital structure","Financing changes who bears cash-flow risk",["Debt creates promised payments and potential tax or discipline effects, but also increases default pressure. Equity absorbs more business risk and has no promised maturity payment, but issuing it can dilute ownership and convey information to the market.","The supplied notes mention pecking-order intuition: firms often prefer internal funds, then debt, then new equity. Treat this as a tendency explained by information and issuance costs, not an absolute law."],[],"Why might two identical projects have different equity risk when financed with different debt levels?"),
        S("Working capital","Value can fail through timing",["Working-capital management coordinates cash, inventory, receivables and payables. Growth frequently consumes cash before it creates cash: inventory is purchased and wages are paid before customers settle invoices.","Net working capital is a balance-sheet measure, while the cash conversion cycle is a timing measure. Use both; neither alone proves liquidity quality."],[],"How can rapid sales growth create a short-term cash shortage?")
      ],
      timelines:[T("Three connected corporate decisions","Work from the productive choice to funding and then to daily execution.",[
        R("Investment",[E("Step 1","Forecast project cash flows","Include only incremental effects","focal"),E("Step 2","Evaluate NPV","Use risk-matched required return","inflow")]),
        R("Financing",[E("Step 3","Choose debt/equity mix","Assess cost, flexibility and distress risk"),E("Step 4","Secure funds","Contract before cash is needed","inflow")]),
        R("Operations",[E("Step 5","Buy inputs / assets","Initial and working-capital outflows","outflow"),E("Step 6","Collect operating cash","Monitor inventory, receivables and payables","inflow")])
      ],"A positive-NPV investment is the value source; financing and working-capital choices make execution feasible.","Firm perspective")],
      termsExtra:[["Capital budgeting","Thẩm định dự án đầu tư"],["Capital structure","Cơ cấu vốn"],["Working-capital management","Quản lý vốn lưu động"]],
      guidedPractice:[
        P("Easy","Name the decision","Classify each action: buying a new machine, issuing bonds, tightening customer credit terms.","Match asset choice, funding choice and operating-current-asset choice.",["Buying machine: capital budgeting.","Issuing bonds: capital structure/financing.","Tightening credit terms: working-capital management."],"Investment; financing; working capital.","The three decisions interact but answer different questions."),
        P("Intermediate","Sunk or incremental?","A firm paid VND 200 million for research last year and must spend VND 3 billion today to launch a product. Which amount enters today's NPV decision?", "Ask which cash flow changes because of today's accept/reject choice.",["The VND 200 million research payment is already incurred and cannot be recovered.","The VND 3 billion launch cost occurs only if the project is accepted.","Include other opportunity costs and side effects caused by launch."],"Exclude the sunk VND 200 million; include the incremental VND 3 billion and other incremental effects.","NPV compares future consequences of today's alternatives."),
        P("Advanced","Growth and cash pressure","A profitable wholesaler doubles sales, offers 60-day credit, holds 30 days of inventory and must pay suppliers in 15 days. Explain the financing gap.","Place payment to suppliers and collection from customers on a timeline.",["Cash is paid around day 15 after purchase.","Inventory may be held around 30 days before sale.","Customer cash arrives around 60 days after sale, much later than supplier payment.","Faster growth increases the amount trapped in this timing gap, requiring working-capital financing."],"Profit can rise while external short-term financing needs also rise.","Accounting margin does not reveal the timing of operating cash.")
      ]
    },
    "intro/business-organization":{
      deepDive:[
        S("Control and liability","Legal form allocates rights and downside",["A sole proprietorship concentrates ownership and control but normally exposes the owner to unlimited personal liability. A partnership pools more resources and expertise but must define authority, profit sharing, continuity and liability. A corporation is a separate legal entity with limited shareholder liability and transferable ownership claims.","Limited liability does not mean the business cannot default; it generally limits the shareholder's loss to the investment, subject to law, guarantees and misconduct."],[],"If a shareholder personally guarantees a corporate loan, is the guarantee protected by limited liability?"),
        S("Capital access and continuity","Transferability changes financing capacity",["Corporations can issue standardized securities and continue despite changes in individual ownership. That continuity and transferability make it easier to pool funds from many investors.","Small business forms may be cheaper and simpler, but raising large-scale external capital is harder when ownership interests are illiquid or when the organization ends after an owner's withdrawal or death."],[],"Why does transferability make a claim more attractive to an outside investor?"),
        S("Taxes and governance","No form is universally best",["Choice of form depends on scale, regulation, tax treatment, liability, financing needs and desired control. Tax rules vary by jurisdiction and can change, so a course comparison should state the general mechanism rather than assume one universal rate.","Corporate separation creates governance benefits through professional management and governance costs through agency conflict. The correct choice is therefore contextual, not a memorized ranking."],[],"Which matters more for a one-person low-risk consultancy: public market access or administrative simplicity?")
      ],
      timelines:[T("Decision path for choosing an organization form","Use a sequence of filters rather than memorizing a single 'best' form.",[
        R("Ownership and control",[E("Step 1","Count owners","One, a few, or many potential investors","focal"),E("Step 2","Set control needs","Direct owner control or delegated management","neutral")]),
        R("Risk and continuity",[E("Step 3","Assess liability","Can owners bear unlimited exposure?","outflow"),E("Step 4","Plan continuity","What happens when an owner exits?","neutral")]),
        R("Capital and cost",[E("Step 5","Estimate funding need","Will transferable securities be needed?","inflow"),E("Step 6","Compare tax/admin burden","Use current jurisdiction-specific rules","outflow")])
      ],"Stop at the first form that fails a non-negotiable requirement, then compare tax and administrative costs among feasible choices.","Founder perspective","Decision process")],
      termsExtra:[["Unlimited liability","Trách nhiệm vô hạn"],["Limited liability","Trách nhiệm hữu hạn"],["Transferability","Khả năng chuyển nhượng"]],
      guidedPractice:[
        P("Easy","Identify the form","One owner controls a business and is personally responsible for its debts. Which general form best fits?", "Focus on ownership count and liability.",["One owner suggests sole proprietorship.","Personal responsibility for business debts confirms unlimited-liability form."],"Sole proprietorship.","The question tests legal-economic attributes, not company size."),
        P("Intermediate","Choose for external equity","Three founders expect to raise capital from many passive investors and want ownership interests to be transferable. Which structure is generally most suitable and why?", "Match the needs to legal separation and security issuance.",["Many passive investors need standardized ownership claims.","Transferability and continuity reduce exit and succession problems.","Limited liability makes the maximum investor exposure clearer."],"A corporation is generally most suitable.","The structure supports capital pooling and transferable shares."),
        P("Advanced","Trade-off memo","A family firm values control but needs major expansion capital. Explain two benefits and two costs of incorporating and selling shares.","Separate financing advantages from governance consequences.",["Benefits: broader capital access and limited liability/continuity.","Costs: ownership dilution and new disclosure/governance obligations.","Potential agency conflict increases when outside owners rely on managers."],"There is no automatic choice; compare the value of capital access with lost control and governance cost.","Organization form is a bundle of claims, controls and obligations.")
      ]
    },
    "intro/agency-goal":{
      deepDive:[
        S("Agency relationship","Delegation creates both specialization and conflict",["Shareholders delegate operating decisions because professional managers can specialize and because thousands of owners cannot all manage the firm. The benefit is scale and expertise. The cost is that managers may have different information, incentives and horizons from owners.","Agency problems include excessive perks, empire building, hiding poor performance, avoiding worthwhile risk or taking excessive risk when downside is shifted to creditors."],[],"Can a manager be too conservative from shareholders' perspective? Give one reason."),
        S("Goal of finance","Value is forward-looking and risk-adjusted",["Maximizing current accounting profit is incomplete because it ignores timing, risk, investment needs and accounting choices. Shareholder wealth is linked to the present value of expected future cash flows attributable to owners.","Value maximization is constrained by law, contracts and ethical duties. Damaging employees, customers or the environment can create legal, reputational and operating costs that reduce long-run cash flows and increase risk."],[],"Why can cutting maintenance raise this year's profit but reduce firm value?"),
        S("Governance mechanisms","No single control solves agency conflict",["Boards, compensation, ownership, disclosure, auditing, debt covenants, product-market competition and takeover threats can align or discipline managers. Each mechanism also has limits and costs.","Performance pay can motivate value creation but can also encourage manipulation or excessive short-term risk if the metric is poorly designed. Good governance uses multiple controls and measures outcomes over an appropriate horizon."],[],"How might a bonus based only on revenue distort decisions?")
      ],
      timelines:[T("Governance feedback loop","Agency control is continuous, not a one-time appointment.",[
        R("Delegate",[E("1","Owners elect board","Monitoring authority is delegated","focal"),E("2","Board appoints management","Strategy and operating authority are assigned","neutral")]),
        R("Measure",[E("3","Management acts","Information is partly private","outflow"),E("4","Reports and audits","Performance and risk become observable","inflow")]),
        R("Correct",[E("5","Board rewards or intervenes","Compensation, advice or replacement","neutral"),E("6","Owners vote / market reacts","Feedback changes future incentives","inflow")])
      ],"The loop repeats as strategy, performance and risk change.","Owners and board","Governance process")],
      sourceCorrections:[
        {title:"Avoid universal claims about governance percentages",body:"Board-independence requirements and whether the CEO may also chair the board depend on jurisdiction, listing rules and time. Learn the economic logic—monitoring independence and accountability—rather than memorizing an unsupported universal percentage."},
        {title:"Sustainability evidence is not one-directional",body:"Do not state that stakeholder-oriented policies never improve return or always improve it. Their financial effect depends on cost, regulation, reputation, risk reduction and execution. Evaluate expected cash-flow and risk channels."}
      ],
      termsExtra:[["Agency conflict","Xung đột đại diện"],["Delegated monitoring","Giám sát được ủy quyền"],["Managerial entrenchment","Sự cố thủ của nhà quản lý"]],
      guidedPractice:[
        P("Easy","Profit versus value","A manager rejects maintenance to increase this year's profit, causing higher expected repair costs next year. Which objective is being neglected?", "Look beyond the current reporting period.",["Current profit rises because expense is postponed.","Expected future cash outflows and operational risk rise.","Present value of owner cash flows may fall."],"Long-term shareholder value is being neglected.","Value includes all future risk-adjusted consequences."),
        P("Intermediate","Design a better bonus","A sales-only bonus causes managers to offer credit to weak customers. Propose two improvements.","Add quality and collection consequences to the metric.",["Include collected cash or bad-debt-adjusted margin, not gross sales alone.","Use a multi-period measurement or clawback so later defaults affect compensation.","Add risk/compliance thresholds."],"Use balanced, risk-adjusted and longer-horizon performance measures.","Incentives should reward value, not an easily manipulated proxy."),
        P("Advanced","Debt-holder conflict","After borrowing, shareholders support a very risky project with negative total NPV but large upside to equity if successful. Identify the agency problem.","Compare who receives upside and who bears downside.",["Limited liability caps shareholder downside.","Much of failure cost falls on lenders through default.","Shareholders may prefer risk that reduces total firm value because upside is shifted toward them."],"Asset substitution/risk shifting between shareholders and creditors.","Agency conflict can occur among claimholders, not only between managers and shareholders.")
      ]
    },
    "intro/financial-system":{
      deepDive:[
        S("Core functions","The system moves funds, risk and information",["The financial system channels purchasing power from surplus units to deficit units, enables payments, creates liquidity, produces information and reallocates risk. Markets and institutions are mechanisms for completing these functions, not goals in themselves.","A well-functioning system reduces frictions so more positive-value exchanges can occur. It does not eliminate credit risk, price risk or conflicts of interest."],[],"Name one function performed by a payment system that is not project valuation."),
        S("Direct and indirect finance","Follow the balance sheets",["In direct finance, the ultimate borrower issues a claim held by the ultimate lender, even though brokers or investment banks may help arrange the transaction. In indirect finance, an intermediary issues its own claim to savers and holds a separate claim on borrowers.","A bank deposit and a bank loan illustrate indirect finance: the depositor does not directly own the household's mortgage. The bank transforms denomination, maturity, liquidity and risk."],[],"Why does using a broker not automatically make a bond purchase indirect finance?"),
        S("Economic development","Allocation quality matters",["Finance supports growth when funds reach productive uses, risks are allocated to willing bearers and payments settle reliably. Poor information, weak contracts or high transaction costs can block worthwhile investment.","More financial activity is not always better. Excess leverage, mispriced risk and fragile maturity transformation can amplify crises. Evaluate efficiency and resilience together."],[],"How can maturity transformation create both usefulness and fragility?")
      ],
      timelines:[T("Flow of funds through the financial system","Compare who issues the claim held by the saver.",[
        R("Direct finance",[E("1","Saver provides funds","May use broker or underwriter","outflow"),E("2","Borrower issues security","Bond or share is the direct claim","focal"),E("3","Borrower invests funds","Real activity may create future cash","inflow")]),
        R("Indirect finance",[E("1","Saver holds intermediary claim","For example, a bank deposit","inflow"),E("2","Intermediary screens and transforms","Pools funds and manages contracts","focal"),E("3","Borrower owes intermediary","For example, a bank loan","outflow")])
      ],"Ask: does the saver hold the borrower's claim, or the intermediary's claim?","System perspective")],
      termsExtra:[["Surplus unit","Đơn vị thặng dư vốn"],["Deficit unit","Đơn vị thiếu vốn"],["Maturity transformation","Chuyển đổi kỳ hạn"]],
      guidedPractice:[
        P("Easy","Direct or indirect?","A company issues new bonds that are purchased by a pension fund. Classify the financing channel.","Identify the claim held by the fund.",["The pension fund holds the company's bond.","The company receives funding from issuance.","An arranger may help, but the ultimate claim is direct."],"Direct finance in the primary market.","The issuer's security connects ultimate borrower and lender."),
        P("Intermediate","Bank intermediation","A household deposits VND 500 million; the bank lends part of pooled deposits to a business. Explain two transformations.","Compare the deposit contract with the loan contract.",["Denomination transformation: many deposits can fund a larger loan.","Maturity/liquidity transformation: deposits may be withdrawable earlier than the business loan matures.","Risk/information transformation: the bank screens and diversifies loans."],"The bank changes the size, maturity, liquidity and risk characteristics of claims.","The depositor owns a bank claim, not a specific business loan."),
        P("Advanced","System resilience","Why can an intermediary be solvent in long-run value but illiquid today?", "Separate asset value from payment timing.",["Long-term loans may have value greater than liabilities, implying positive net worth.","Depositors or short-term creditors may demand cash before loans mature.","The institution can fail to meet immediate payments without being economically insolvent under orderly liquidation."],"Maturity mismatch can create liquidity stress even when asset value is sufficient.","Timing is central at both individual-contract and system levels.")
      ]
    }
  });
})();
