"use strict";
(() => {
  const H=window.FM_DEEP;if(!H)return;const {S,P,E,R,T,register}=H;
  register({
    "markets/market-map":{
      deepDive:[
        S("Three classification axes","One transaction has several labels",["Debt versus equity classifies the claim. Primary versus secondary classifies whether the claim is newly issued. Money versus capital market classifies mainly by original maturity and instrument type. Exchange versus OTC classifies trading organization.","These axes are independent. A newly issued 90-day commercial paper note is primary-market, money-market debt; its later resale would be secondary-market money-market debt."],[],"Classify a newly issued 10-year corporate bond on all three relevant axes."),
        S("Primary and secondary roles","Issuer funding and investor liquidity are connected",["In the primary market, the issuer receives funds from selling a new claim. In the secondary market, existing claims change hands and the original issuer normally receives no new cash.","Secondary markets still matter to issuers because liquidity and observable prices affect how much investors will pay for new issues. A liquid secondary market can lower required returns and financing cost."],[],"Why can a secondary-market price affect a future primary issue?"),
        S("Money and capital markets","Original maturity prevents reclassification",["Money-market instruments are short-term debt, commonly defined by original maturity of one year or less. Capital markets contain longer-term debt and equity. A long-term bond with only three months remaining does not become a newly issued money-market instrument; its original maturity and market convention remain relevant.","Short maturity generally reduces price sensitivity, but does not eliminate default or liquidity risk."],[],"Is common stock ever a money-market instrument because an investor plans to hold it for one month?")
      ],
      timelines:[T("Life of a security","Issuance and later trading are different market stages.",[
        R("Primary stage",[E("t = 0","Issuer creates security","New bond/share offered","focal"),E("t = 0","Investor cash → issuer","Issuer receives financing","inflow")]),
        R("Secondary stage",[E("Later","Investor A sells","Existing security changes owner","outflow"),E("Later","Investor B pays A","Issuer normally receives no cash","inflow")]),
        R("Contract cash flows",[E("Scheduled dates","Issuer pays claimholders","Coupon, dividend or principal per contract","outflow")])
      ],"Do not call every purchase 'primary'; ask whether the claim is newly issued and who receives the purchase cash.","Market-system view")],
      termsExtra:[["Original maturity","Kỳ hạn ban đầu"],["Underwriting","Bảo lãnh phát hành"],["Price discovery","Khám phá giá"]],
      guidedPractice:[
        P("Easy","Classify commercial paper","A corporation issues a new 180-day unsecured note to a fund. Classify it.","Use claim, issuance stage and original maturity.",["It is debt because repayment is promised.","It is primary because newly issued.","It is money market because original maturity is under one year."],"Primary-market money-market debt.","One transaction can carry multiple compatible classifications."),
        P("Intermediate","Existing stock trade","An investor buys an existing listed share from another investor. Does the company receive financing?", "Trace the purchase cash.",["Buyer pays the selling investor.","The share already existed.","The issuer receives no new issue proceeds, although market price affects future financing conditions."],"Secondary equity-market transaction; no direct new funding to issuer.","Secondary liquidity supports, but is not itself, primary financing."),
        P("Advanced","Remaining maturity trap","A 10-year bond has 6 months remaining. Is it automatically a money-market security? Explain.","Separate original maturity from remaining time.",["The bond was issued as long-term capital-market debt.","Its remaining duration is short, so price sensitivity may resemble short debt.","Classification in course materials generally follows original maturity and instrument market."],"No; it remains a capital-market bond with short remaining maturity.","Holding horizon and remaining maturity do not redefine the original instrument category.")
      ]
    },
    "markets/transaction-costs":{
      deepDive:[
        S("Types of friction","Transaction cost is broader than commission",["Search, verification, contracting, trading, custody, monitoring, enforcement and learning all consume resources. Fixed costs make small transactions especially expensive per unit.","These costs can prevent mutually beneficial financing even when a borrower has a positive-value project and a saver has funds."],[],"Give one pre-contract and one post-contract transaction cost."),
        S("Economies of scale","Pooling spreads fixed cost",["A financial intermediary or fund can purchase in large blocks, specialize in analysis and reuse systems across many customers. Average cost falls as fixed infrastructure and expertise are spread over more assets.","Scale is not automatically efficient forever: complexity, bureaucracy and concentration can create new costs."],[],"Why might a small investor prefer a diversified fund to buying 100 securities separately?"),
        S("Expertise and standardization","Institutions transform process quality",["Standard contracts, credit scoring, settlement systems and repeated relationships reduce the cost of each decision. Specialists can also monitor borrowers more effectively than dispersed individuals.","The benefit is not that institutions know everything; it is that they can produce and act on information at lower cost per unit."],[],"How does a standardized loan contract reduce negotiation cost?")
      ],
      timelines:[T("From saver to funded project","Transaction costs appear at several points, not only at the trade.",[
        R("Before contract",[E("1","Search and screen","Find counterparty; assess risk","outflow"),E("2","Negotiate and document","Specify price, collateral and covenants","outflow")]),
        R("At transaction",[E("3","Execute and settle","Transfer cash and legal claim","focal")]),
        R("After contract",[E("4","Monitor and service","Collect data and payments","outflow"),E("5","Enforce or restructure","Act if terms are breached","outflow")])
      ],"An intermediary creates value when the cost saved or risk improved exceeds its fees and operating cost.","Contract life cycle")],
      termsExtra:[["Economies of scale","Kinh tế theo quy mô"],["Search cost","Chi phí tìm kiếm"],["Enforcement cost","Chi phí thực thi hợp đồng"]],
      guidedPractice:[
        P("Easy","Identify fixed cost","A legal review costs 5,000 whether a bond purchase is 50,000 or 5 million. Why does scale matter?", "Compute cost as percentage of transaction.",["For 50,000, cost is 10%.","For 5 million, cost is 0.1%."],"The same fixed cost is much smaller per unit at large scale.","Pooling can make investments economical that are too costly individually."),
        P("Intermediate","Fund fee comparison","An investor can buy 50 securities separately at 20 transaction cost each or buy a fund for an annual fee of 400. Compare direct initial trading cost.","Count direct trades; ignore other differences for this narrow calculation.",["Direct cost=50×20=1,000.","Fund fee=400 for the stated year.","Direct cost exceeds fee by 600, before considering fund management, repeated fees and other costs."],"Initial narrow comparison favors fund by 600.","A full decision would include ongoing fees, diversification and tracking quality."),
        P("Advanced","When scale fails","Explain why a very large intermediary may still produce poor outcomes despite lower unit trading cost.","Look for complexity, incentives and concentration.",["Complex products can be difficult to monitor internally.","Managers may pursue growth rather than customer value.","Operational concentration can make failures systemically costly.","Scale economies can be offset by diseconomies and agency problems."],"Scale lowers some costs but does not guarantee good allocation or governance.","Efficiency requires both cost advantage and incentive/control quality.")
      ]
    },
    "markets/asymmetric-info":{
      deepDive:[
        S("Definition","Relevant information is unevenly distributed",["Asymmetric information exists when one party has more or better information relevant to a financial contract. Borrowers usually know more about project quality and intended behavior than outside lenders.","The problem is not merely that information is incomplete; it is that the incompleteness is uneven and can be strategically used."],[],"If both sides are equally uncertain about a weather event, is that necessarily asymmetric information?"),
        S("Before and after contract","Timing identifies the problem",["Adverse selection occurs before contracting: hidden type makes risky borrowers or low-quality securities more likely to accept pooled terms. Moral hazard occurs after contracting: hidden action changes because the contract reallocates consequences.","The same relationship may contain both problems, so screening and monitoring solve different stages."],[],"Credit scoring mainly targets which stage?"),
        S("Contract responses","Information problems shape financial structure",["Collateral, net worth, disclosure, covenants, deductibles, monitoring, reputation and relationship lending can reduce information cost or change incentives. These mechanisms are costly and imperfect.","Financial intermediaries can avoid some free-rider problems because they hold private, nontraded loans and capture more benefit from information production."],[],"Why can publicly revealing purchased research reduce the researcher's ability to recover its cost?")
      ],
      timelines:[T("Information problems across a contract","Use the contract date to separate hidden type from hidden action.",[
        R("Before signing",[E("Screening","Hidden type","Borrower knows quality/risk better","outflow"),E("Selection","Contract offered","Risky types may accept more readily","focal")]),
        R("After signing",[E("Monitoring","Hidden action","Borrower may change behavior","outflow"),E("Enforcement","Outcome and repayment","Covenants/collateral affect consequences","inflow")])
      ],"Adverse selection is primarily before; moral hazard is primarily after.","Lender perspective")],
      termsExtra:[["Hidden type","Đặc điểm ẩn"],["Hidden action","Hành vi ẩn"],["Free-rider problem","Vấn đề người đi nhờ"]],
      guidedPractice:[
        P("Easy","Name the problem","A borrower knows before applying that its project is far riskier than the lender can observe. Which problem?", "The information difference exists before contract.",["Hidden project quality is a hidden type.","It affects who applies and on what terms."],"Adverse selection.","Timing before contracting is the key diagnostic."),
        P("Intermediate","Choose a response","After receiving an unsecured loan, a firm shifts funds into a much riskier project. Identify the problem and one contract response.","This is behavior after cash is advanced.",["Problem: moral hazard/risk shifting.","Response: covenant limiting asset risk, monitoring use of funds, collateral, or staged disbursement."],"Moral hazard; use monitoring and incentive-compatible contract terms.","Screening type alone cannot control later behavior."),
        P("Advanced","Free-rider logic","An analyst spends heavily to identify an undervalued public bond, but other traders copy the resulting trade and price movement. Explain why too little private information may be produced.","Compare private cost with privately captured benefit.",["Analyst bears research cost.","Other traders gain from the price signal without paying.","Copying erodes the analyst's excess return.","If benefits cannot be captured, fewer analysts will pay to produce information."],"Free riding makes information a partially public good and can reduce private production.","This helps explain specialized intermediaries and regulation/disclosure.")
      ]
    },
    "markets/lemons":{
      deepDive:[
        S("Pooling price","Average pricing can drive out quality",["When buyers cannot distinguish high- from low-quality claims, they offer a price based on average expected quality. High-quality issuers may view that price as too low and withdraw, lowering average quality further.","The market can shrink or disappear even though mutually beneficial trades with good issuers exist."],[],"Why does a lower pooled price disproportionately discourage high-quality sellers?"),
        S("Credit version","Average interest can repel safe borrowers",["If lenders cannot identify borrower risk, they may charge a pooled rate. Safe borrowers may reject it, leaving a riskier applicant pool. Raising the rate can also attract riskier projects or change borrower behavior.","Credit rationing can therefore occur: lenders may limit quantity rather than clear the market only by raising rates."],[],"Why might a lender refuse to lend more even when a borrower offers a higher rate?"),
        S("Market repairs","Signals must be credible and costly to fake",["Audited disclosure, warranties, collateral, retained ownership, reputation, certification and underwriting can signal or verify quality. A signal works only when low-quality parties find it sufficiently costly to imitate.","Regulation can improve standardized disclosure, but enforcement and audit quality determine credibility."],[],"Why is an unaudited promise of quality a weak signal?")
      ],
      timelines:[T("Lemons spiral","Hidden quality changes participation and therefore the pool itself.",[
        R("Initial market",[E("1","Mixed quality","Buyer observes only average","focal"),E("2","Pooled price offered","Below good seller's value","outflow")]),
        R("Selection response",[E("3","Good sellers withdraw","Average quality falls","outflow"),E("4","Buyer lowers price again","More good sellers exit","outflow")]),
        R("Possible outcome",[E("5","Thin or failed market","Good trades are lost","neutral")])
      ],"This is a self-reinforcing participation problem, not merely one buyer making a bad estimate.","Market perspective")],
      termsExtra:[["Pooling equilibrium","Cân bằng gộp"],["Signal","Tín hiệu chất lượng"],["Credit rationing","Hạn chế tín dụng"]],
      guidedPractice:[
        P("Easy","Used-asset analogy","Good assets are worth 100 to sellers, bad assets 40; buyers cannot tell type and offer 70. Who exits first?", "Compare offer with each seller's reservation value.",["Good sellers reject 70 because 70<100.","Bad sellers accept because 70>40."],"Good-quality sellers exit first.","The resulting pool becomes worse than buyers originally expected."),
        P("Intermediate","Expected pooled value","A claim pays 120 if good and 30 if bad. Buyers believe 60% are good. Ignoring discounting, what pooled expected value is offered?", "Probability-weight the two payoffs.",["EV=0.60×120+0.40×30=72+12."],"Pooled expected value = 84.","If good sellers require more than 84, their withdrawal changes the probability mix."),
        P("Advanced","Design a signal","Propose a signal that separates strong from weak issuers and explain the separating condition.","A credible signal must be cheaper for strong issuers or more costly for weak ones.",["Example: retain a meaningful first-loss stake or pledge collateral.","Strong issuers expect lower loss and can bear the signal at lower expected cost.","Weak issuers find imitation too costly, so the signal conveys information."],"A separating signal has different incentive cost across types and is verifiable.","Cheap talk that all types can copy cannot solve the lemons problem.")
      ]
    },
    "markets/moral-hazard":{
      deepDive:[
        S("Incentive shift","Contracts change marginal benefits and costs",["After funds or insurance are provided, the protected party may take actions that raise private benefit while shifting part of the downside to another party. Hidden action and imperfect enforcement create moral hazard.","The issue is not bad character alone; it is a predictable response to altered incentives and information."],[],"How can limited liability increase risk-taking incentives?"),
        S("Principal-agent problem","Managers control resources owned by others",["Shareholders are principals and managers are agents. Managers may enjoy perks, avoid effort, pursue empire size or manipulate reports. Dispersed owners can free ride on monitoring, weakening control.","Debt can reduce free cash available for perks but creates new conflicts with creditors. No financing instrument eliminates agency cost."],[],"Why might debt discipline managers and simultaneously encourage risk shifting?"),
        S("Covenants and monitoring","Control must preserve useful flexibility",["Affirmative covenants require actions such as reporting; negative covenants restrict actions such as additional borrowing or asset sales. Collateral and net-worth requirements protect lender recovery and borrower incentives.","Overly restrictive terms can block value-creating adaptation. Contract design balances incentive control with operating flexibility."],[],"Why might a covenant include a waiver process?")
      ],
      timelines:[T("Moral hazard after funding","Behavior changes after the lender's cash is committed.",[
        R("Contract",[E("t = 0","Loan disbursed","Terms based on expected behavior","inflow")]),
        R("Hidden action",[E("After t = 0","Borrower chooses effort/risk","Lender observes imperfectly","outflow"),E("Monitoring dates","Reports / covenant tests","Information is updated","focal")]),
        R("Outcome",[E("Repayment date","Repay or default","Consequences shared by contract","neutral")])
      ],"Screen before t=0; monitor and incentivize after t=0.","Lender perspective")],
      termsExtra:[["Covenant","Điều khoản ràng buộc"],["Risk shifting","Chuyển dịch rủi ro"],["First-loss position","Vị thế chịu lỗ đầu tiên"]],
      guidedPractice:[
        P("Easy","Before or after?","An insured driver becomes less careful after purchasing full coverage. Classify the problem.","Behavior changes after contract.",["Coverage reduces the driver's marginal cost of an accident.","Care is difficult for insurer to observe continuously."],"Moral hazard.","The hidden action occurs after insurance is in force."),
        P("Intermediate","Covenant purpose","A loan contract prohibits dividends if net worth falls below a threshold. What risk does this control?", "Ask how dividends affect assets available to lenders.",["Dividends transfer assets to shareholders.","When net worth is low, the transfer can reduce creditor protection.","Restriction preserves a loss-absorbing cushion."],"It limits wealth transfer from creditors to shareholders and protects repayment capacity.","Covenants alter incentives before default occurs."),
        P("Advanced","Optimal restriction","Why might a lender allow some additional debt rather than ban it entirely?", "Consider valuable future projects and renegotiation cost.",["New debt may finance positive-NPV opportunities.","An absolute ban can destroy value and weaken repayment capacity.","A threshold, priority rule or consent process controls dilution while preserving flexibility."],"Efficient covenants minimize total contracting and agency cost, not all borrower freedom.","Control has opportunity cost.")
      ]
    },
    "markets/intermediaries":{
      deepDive:[
        S("Balance-sheet transformation","Intermediaries create new claims",["Depository institutions issue deposits and hold loans/securities. Insurance companies collect premiums and hold assets against contingent claims. Funds issue shares and hold portfolios. Finance companies borrow in markets and make specialized loans.","Classify an institution by both how it raises funds and what assets or services it provides."],[],"Why is a bank loan indirect finance even if the bank later securitizes it?"),
        S("Risk sharing and liquidity","Pooling changes exposure",["Pooling many independent risks can make aggregate outcomes more predictable. Intermediaries can offer liquid claims while holding less-liquid assets, provide denomination transformation and facilitate payments.","These services create liquidity and maturity risk if short-term claims are promised against long-term assets."],[],"Why can a bank run occur even if most loans eventually repay?"),
        S("Information production","Private loans help capture research benefit",["Intermediaries screen, monitor and build relationships. Because bank loans are not continuously traded like public bonds, the bank can retain more of the value from proprietary information and reduce free riding.","Delegated monitoring avoids every saver independently duplicating the same investigation."],[],"What cost would arise if every small depositor had to inspect every bank borrower?")
      ],
      timelines:[T("Intermediation balance-sheet chain","The saver and borrower hold different contracts with the institution.",[
        R("Funding side",[E("1","Saver → intermediary","Deposit, premium or fund subscription","inflow"),E("2","Intermediary issues claim","Liability or fund share to saver","outflow")]),
        R("Asset side",[E("3","Intermediary → borrower/market","Loan or security purchase","outflow"),E("4","Borrower repayment / asset return","Funds intermediary obligations","inflow")]),
        R("Service layer",[E("Throughout","Screen, monitor, diversify","Transformation creates value and risk","focal")])
      ],"Do not collapse the two contracts: saver claim on intermediary and intermediary claim on borrower are distinct.","Intermediary perspective")],
      termsExtra:[["Delegated monitoring","Giám sát được ủy quyền"],["Denomination transformation","Chuyển đổi quy mô khoản vốn"],["Contractual savings institution","Tổ chức tiết kiệm theo hợp đồng"]],
      guidedPractice:[
        P("Easy","Identify funding source","A finance company issues commercial paper and bonds, then makes auto loans. Is it a depository institution?", "Ask whether it accepts deposits.",["Funding comes from market debt, not customer deposits.","Assets are consumer loans."],"No; it is a nondepository finance intermediary.","Intermediaries differ in funding structure."),
        P("Intermediate","Two claims","A depositor places 100 in a bank that lends 80 to a firm. What claims exist?", "Separate depositor-bank and bank-firm relationships.",["Depositor owns a bank deposit asset; bank owes the deposit liability.","Bank owns a loan receivable; firm owes the loan liability."],"Two distinct contracts: deposit and loan.","Indirect finance inserts the intermediary's balance sheet between saver and borrower."),
        P("Advanced","Maturity transformation stress","A bank funds 10-year fixed-rate loans with withdrawable deposits. Rates rise and depositors withdraw. Explain two risks.","Consider liquidity timing and market value of fixed-rate assets.",["Liquidity risk: loans cannot be collected immediately to meet withdrawals.","Interest-rate risk: existing fixed-rate loans fall in market value when rates rise.","Forced sales can realize losses."],"The same maturity transformation that provides useful long loans and liquid deposits creates fragility.","Transformation benefits must be supported by capital, liquidity and risk management.")
      ]
    },
    "markets/money-instruments":{
      deepDive:[
        S("Instrument map","Issuer, promise, collateral and trading differ",["Treasury bills are government discount debt. Commercial paper is short-term unsecured corporate or financial-company debt. Negotiable CDs are transferable bank time deposits. Federal funds are very short-term interbank reserve loans. Repos are collateralized cash loans structured as sale and repurchase of securities. Bankers' acceptances are bank-guaranteed time drafts often linked to trade.","Memorize a comparison matrix, not isolated definitions: issuer, purpose, maturity, quote convention, collateral/guarantee, secondary liquidity and default exposure."],[],"Which instrument is a bank deposit and which is a bank-guaranteed trade draft?"),
        S("Risk is relative","Short-term does not mean risk-free",["T-bills have very low default risk in their own currency and deep liquidity, but market price can still change before maturity. Commercial paper depends on issuer credit and backup liquidity. Repos depend on counterparty, collateral quality, haircut and settlement mechanics.","Negotiable CDs are bank credit claims, not identical to government obligations."],[],"How does a repo haircut protect the cash lender?"),
        S("Marketability","A secondary market can be deep, thin or absent",["Treasury bills trade actively. Negotiable CDs and bankers' acceptances can trade. Commercial paper may have dealer support but secondary trading is typically thinner because issues are short and often held to maturity. Federal funds are loans rather than standardized securities with a conventional resale market.","Avoid categorical statements when liquidity depends on issue size, credit, maturity and market conditions."],[],"Why might two instruments with the same maturity have different liquidity?")
      ],
      timelines:[
        T("Repo mechanics","Cash and collateral move in opposite directions, then reverse.",[
          R("Start date",[E("Day 0","Cash lender pays cash","Economically lends funds","outflow"),E("Day 0","Cash borrower transfers securities","Collateral is delivered","inflow")]),
          R("Maturity",[E("Day d","Borrower repurchases securities","Pays original cash + repo interest","outflow"),E("Day d","Lender returns collateral","Transaction reverses","inflow")])
        ],"A repo is collateralized financing structured as a sale and later repurchase of securities.","Cash lender perspective"),
        T("Single-price Treasury-bill auction","Noncompetitive bids are filled first; competitive bids are ranked by yield.",[
          R("Submission",[E("1","Treasury announces offering","Amount and maturity specified","focal"),E("2","Investors submit bids","Competitive: amount + yield; noncompetitive: amount","neutral")]),
          R("Allocation",[E("3","Fill noncompetitive bids","Subject to auction rules/limits","inflow"),E("4","Rank competitive bids","Lowest yield/highest price first","neutral")]),
          R("Clearing",[E("5","Find stop-out yield","Highest accepted competitive yield","focal"),E("6","Prorate marginal bids","If demand at stop-out exceeds remainder","neutral")]),
          R("Settlement",[E("7","Apply single price","Successful bidders receive stop-out price","outflow")])
        ],"All successful bidders receive the stop-out price; marginal bids at the stop-out yield may be prorated.","Auction process","Process timeline")
      ],
      sourceCorrections:[
        {title:"Commercial paper secondary trading is thin, not universally nonexistent",body:"Commercial paper is commonly held to maturity and secondary liquidity is limited compared with Treasury bills, but dealer-facilitated resale can occur. Avoid an absolute 'no secondary market' rule."},
        {title:"Individuals can obtain money-market exposure",body:"Large denominations make direct participation difficult in many instruments, but individuals may buy Treasury bills or invest through money-market funds. 'No individual participates' is too absolute."},
        {title:"Repo is a securities sale-repurchase, not a sale of federal funds",body:"The cash borrower sells securities and agrees to repurchase them. Economically it receives a collateralized cash loan; the collateral is usually government or other eligible securities."}
      ],
      termsExtra:[["Haircut","Tỷ lệ chiết khấu tài sản bảo đảm"],["Stop-out yield","Lợi suất cắt thầu"],["Backup line of credit","Hạn mức tín dụng dự phòng"]],
      guidedPractice:[
        P("Easy","Match instrument","Which instrument is a transferable time deposit issued by a bank?", "Look for deposit plus negotiability.",["A negotiable certificate of deposit is a bank time deposit that can be transferred."],"Negotiable CD.","Issuer and legal form distinguish it from commercial paper."),
        P("Intermediate","Repo cash amount","Collateral market value is 10 million and haircut is 3%. How much cash is lent at inception?", "Apply cash=(1−haircut)×collateral value.",["Cash=0.97×10,000,000."],"Cash lent = 9,700,000.","The 300,000 cushion protects against collateral value and liquidation risk."),
        P("Advanced","Auction allocation","Treasury offers 100 million. Noncompetitive bids are 10 million. Competitive bids below the stop-out yield total 75 million; bids at the stop-out yield total 30 million. How much of stop-out bids is allotted?", "Subtract prior allocations, then prorate marginal bids.",["Competitive amount available=100−10=90 million.","After superior competitive bids: 90−75=15 million remains.","Stop-out bids request 30 million, so allotment ratio=15/30=50%."],"Each accepted stop-out bid receives 50% of requested amount.","Single-price allocation accepts best yields first and prorates the marginal block.")
      ]
    },
    "markets/money-yields":{
      deepDive:[
        S("Quotation bases","Same instrument, different reported yields",["Discount yield uses face value and a 360-day year. Bond-equivalent yield uses purchase price and commonly a 365-day year. EAR compounds the actual holding-period growth to one year.","These formulas answer different convention questions; disagreement among results is expected, not an error."],[],"Which yield uses the money actually invested in its denominator?"),
        S("Bid and ask","Price and yield move inversely",["A dealer's bid is the price the dealer pays; ask is the price the customer pays. For a discount instrument, the higher price corresponds to the lower yield. A bid-ask spread compensates dealing and liquidity provision.","Be careful when quotations are expressed as yields: the higher ask price is associated with a lower ask yield."],[],"If ask price exceeds bid price, which yield is normally lower?"),
        S("Holding period first","Build annualization from the actual return",["The actual holding-period return on a pure discount security is (F−P)/P. BEY linearly annualizes it; EAR compounds it. For short d, the figures may be close, but they diverge as return or maturity rises.","Use the day-count convention explicitly given by the course problem."],[],"Why does EAR generally exceed simple annualization when holding-period return is positive?")
      ],
      timelines:[T("Pure-discount security","There is one purchase outflow and one maturity inflow.",[
        R("Purchase",[E("Day 0","− P","Amount actually invested","outflow")]),
        R("Holding period",[E("Days 1…d−1","No coupon","Price may change if sold early","neutral")]),
        R("Maturity",[E("Day d","+ F","Face value received","inflow")])
      ],"Holding-period return=(F−P)/P. Quotation formulas then annualize using their own denominator and day-count convention.","Investor perspective")],
      formulaKeys:["T-bill discount yield","Bond-equivalent yield","Effective annual return"],
      termsExtra:[["Bank-discount basis","Cơ sở chiết khấu ngân hàng"],["Holding-period yield","Lợi suất kỳ nắm giữ"],["Bid-ask spread","Chênh lệch giá mua-bán"]],
      guidedPractice:[
        P("Easy","Discount yield","Face value 10,000, price 9,875, 68 days. Find discount yield.","Use face value and 360 days.",["Dollar discount=125.","DY=125/10,000×360/68."],"DY ≈ 6.62%.","The bank-discount convention understates the return base because it divides by face value."),
        P("Intermediate","BEY and comparison","For the same bill, find BEY and explain why it exceeds DY.","Use price and 365 days.",["BEY=125/9,875×365/68≈0.06794."],"BEY ≈ 6.79%, above 6.62% DY.","BEY uses a smaller denominator (price) and a 365-day annualizer."),
        P("Advanced","EAR","For the same 68-day bill, find effective annual return.","Annualize the gross holding-period factor with compounding.",["Holding gross factor=10,000/9,875.","EAR=(10,000/9,875)^(365/68)−1."],"EAR ≈ 6.99%.","EAR assumes repeated reinvestment at the same holding-period return over a year.")
      ]
    }
  });
})();
